### ISSUE TITLE
 error: package com.davidangulo.randombytes does not exist

### ISSUE THREAD

**Issue by RayHughes** [dcangulo/react-native-pkce-challenge#139]
When upgrading to `5.x` from `3.2`, the following error occurs when building Android.

> Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
> /app/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:49: error: package com.davidangulo.randombytes does not exist
> import com.davidangulo.randombytes.RandomBytesPackage;
>                                   ^
>/app/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:142: error: cannot find symbol

React Native = 0.67.3
buildToolsVersion = "30.0.2"
minSdkVersion = 21
compileSdkVersion = 31
targetSdkVersion = 30
ndkVersion = "21.4.7075529"

**Comment by dcangulo** [comment]
Re-open if the issue still persists on [v5.3.0](https://github.com/dcangulo/react-native-pkce-challenge/releases/tag/v5.3.0).
