### ISSUE TITLE
invalid_grant: PKCE verification failed

### ISSUE THREAD

**Issue by nakulsaini** [dcangulo/react-native-pkce-challenge#229]
Exchange toke request failing with following response.

`{"error":"invalid_grant","error_description":"PKCE verification failed"}`

React Native: 0.68.5
expo-random: ~12.2.0
react-native-pkce-challenge: ^5.1.1

**Comment by dcangulo** [comment]
Re-open if the issue still persists on [v5.3.0](https://github.com/dcangulo/react-native-pkce-challenge/releases/tag/v5.3.0).
