### ISSUE TITLE
Update crypto-js to 4.2.0

### ISSUE THREAD

**Issue by geoffrey-tan** [dcangulo/react-native-pkce-challenge#334]
Possible to update `crypto-js` to `4.2.0`?

> Crypto-js PBKDF2 is 1,000 times weaker than originally specified in 1993, and [at least 1,300,000 times weaker than current industry standard](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#pbkdf2). This is because it both (1) defaults to [SHA1](https://en.wikipedia.org/wiki/SHA-1), a cryptographic hash algorithm considered insecure [since at least 2005](https://www.schneier.com/blog/archives/2005/02/cryptanalysis_o.html) and (2) defaults to [one single iteration](https://github.com/brix/crypto-js/blob/1da3dabf93f0a0435c47627d6f171ad25f452012/src/pbkdf2.js#L22-L26), a 'strength' or 'difficulty' value specified at 1,000 when specified in 1993. PBKDF2 relies on iteration count as a countermeasure to [preimage](https://en.wikipedia.org/wiki/Preimage_attack) and [collision](https://en.wikipedia.org/wiki/Hash_collision) attacks.

See https://github.com/advisories/GHSA-xwcq-pm8m-c4vf

**Comment by bill-pairaktaridis** [comment]
I forked the repo and just updated the package and seems to work fine.

**Comment by bill-pairaktaridis** [comment]
@geoffrey-tan you can use it if you'd like: https://github.com/bill-pairaktaridis/react-native-pkce-challenge

**Comment by geoffrey-tan** [comment]
> @geoffrey-tan you can use it if you'd like: https://github.com/bill-pairaktaridis/react-native-pkce-challenge

Thanks!

**Comment by kohchihao** [comment]
Hi @dcangulo , possible to make a release for this `crypto-js` bump?

**Comment by bill-pairaktaridis** [comment]
Yeah, our team would appreciate that too

**Comment by geoffrey-tan** [comment]
Overriding also works for now:

```
 "overrides": {
    "react-native-pkce-challenge": {
      "crypto-js": "^4.2.0"
    }
  },
```

**Comment by bill-pairaktaridis** [comment]
@geoffrey-tan unfortunately `dependency-review` still fails with the override
