### ISSUE TITLE
Error in Android app build (c++ version)

### ISSUE THREAD

**Issue by cavanierc** [dcangulo/react-native-pkce-challenge#391]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-pkce-challenge@5.3.0` for the project I'm working on.

I have an error when building my android app with `react-native@0.73.*` and `react-native-pkce-challenge@5.3.0`, I think this is because react-native no longer supports c++ 11, using c++ 20 in CMakeLists solves my problem.

Error:
```
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Execution failed for task ':react-native-pkce-challenge:buildCMakeDebug[arm64-v8a]'.
mobile/android/../node_modules/react-native/ReactCommon/jsi/jsi/jsi.h:1107:23 error: no template named 'enable_if_t' in namespace 'std'; did you mean 'enable_if'? typename = std::enable_if_t< ~~~~~^~~~~~~~~~~ enable_if
```

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-pkce-challenge/android/CMakeLists.txt b/node_modules/react-native-pkce-challenge/android/CMakeLists.txt
index b6ea016..44f20fa 100644
--- a/node_modules/react-native-pkce-challenge/android/CMakeLists.txt
+++ b/node_modules/react-native-pkce-challenge/android/CMakeLists.txt
@@ -2,7 +2,7 @@ cmake_minimum_required(VERSION 3.4.1)
 project(PkceChallenge)
 
 set (CMAKE_VERBOSE_MAKEFILE ON)
-set (CMAKE_CXX_STANDARD 11)
+set (CMAKE_CXX_STANDARD 20)
 
 add_library(cpp
             SHARED
```

Do you have the same problem?

All works in iOS.

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by dcangulo** [comment]
[v5.3.1](https://github.com/dcangulo/react-native-pkce-challenge/releases/tag/v5.3.1) release should include the fix for this issue.
