### ISSUE TITLE
[Windows] Error in Android CMake : NODE_MODULES_DIR contains backslashes

### ISSUE THREAD

**Issue by abervoet** [dcangulo/react-native-pkce-challenge#414]
Hello

We have an Android build issue related to this library, on windows.

In the [android\build.gradle#L60](https://github.com/dcangulo/react-native-pkce-challenge/blob/main/android/build.gradle#L60) file, the `NODE_MODULES_DIR` variable outputs a path with backslashes (`\\`) on Windows, which CMake rejects, for example : `NODE_MODULES_DIR=D:\\.....\\android/../node_modules"`

I've found similar issue on other repositories, where the fix is made by doing os-specific formatting in the `build.gradle` file. Eg : 
https://github.com/Kudo/react-native-v8/commit/5a2107fc986cc963470e4fb14ae85c58d41c3520

Another (maybe dirty) solution could be adding something like this to the [CMakeLists.txt#L6](https://github.com/dcangulo/react-native-pkce-challenge/blob/main/android/CMakeLists.txt#L6) file : `string(REPLACE "\\" "/" NODE_MODULES_DIR ${NODE_MODULES_DIR})`

I've tried both solutions locally, they work and allow me to build and run my Android app on Windows.

Could you please provide a fix for windows usage of this library ?
Thanks a lot !

Full error log below, 
```
PS D:\.....> yarn android
yarn run v1.22.19
$ react-native run-android
info A dev server is already running for this project on port 8081.
info Installing the app...

> Task :react-native-pkce-challenge:configureCMakeDebug[arm64-v8a] FAILED
C/C++: CMake Error at CMakeLists.txt:7 (add_library):
C/C++:   Syntax error in cmake code when parsing string
C/C++:     D:\.....\android/../node_modules/react-native/ReactCommon/jsi/jsi/jsi.cpp
C/C++:   Invalid character escape '\w'.
337 actionable tasks: 2 executed, 335 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-pkce-challenge:configureCMakeDebug[arm64-v8a]'.
> [CXX1429] error when building with cmake using D:\......\node_modules\react-native-pkce-challenge\android\CMakeLists.txt: -- Configuring incomplete, errors occurred!
  See also "D:/......./node_modules/react-native-pkce-challenge/android/.cxx/Debug/493k3528/arm64-v8a/CMakeFiles/CMakeOutput.log".

  C++ build system [configure] failed while executing:
      @echo off
      "C:\\.....\\android-sdk\\cmake\\3.22.1\\bin\\cmake.exe" ^
        "-HD:\\......\\node_modules\\react-native-pkce-challenge\\android" ^
        "-DCMAKE_SYSTEM_NAME=Android" ^
        "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" ^
        "-DCMAKE_SYSTEM_VERSION=21" ^
        "-DANDROID_PLATFORM=android-21" ^
        "-DANDROID_ABI=arm64-v8a" ^
        "-DCMAKE_ANDROID_ARCH_ABI=arm64-v8a" ^
        "-DANDROID_NDK=C:\\.....\\android-sdk\\ndk\\25.1.8937393" ^
        "-DCMAKE_ANDROID_NDK=C:\\.....\\android-sdk\\ndk\\25.1.8937393" ^
        "-DCMAKE_TOOLCHAIN_FILE=C:\\.....\\android-sdk\\ndk\\25.1.8937393\\build\\cmake\\android.toolchain.cmake" ^
        "-DCMAKE_MAKE_PROGRAM=C:\\.....\\android-sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
        "-DCMAKE_CXX_FLAGS=-O2 -frtti -fexceptions -Wall -fstack-protector-all" ^
        "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\\.....\\node_modules\\react-native-pkce-challenge\\android\\build\\intermediates\\cxx\\Debug\\493k3528\\obj\\arm64-v8a" ^
        "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=D:\\.....\\node_modules\\react-native-pkce-challenge\\android\\build\\intermediates\\cxx\\Debug\\493k3528\\obj\\arm64-v8a" ^
        "-DCMAKE_BUILD_TYPE=Debug" ^
        "-BD:\\.....\\node_modules\\react-native-pkce-challenge\\android\\.cxx\\Debug\\493k3528\\arm64-v8a" ^
        -GNinja ^
>>>>>   "-DNODE_MODULES_DIR=D:\\.....\\android/../node_modules"  <<<<<
    from D:\.....\node_modules\react-native-pkce-challenge\android
  CMake Error at CMakeLists.txt:7 (add_library):
    Syntax error in cmake code when parsing string

      D:\.....\android/../node_modules/react-native/ReactCommon/jsi/jsi/jsi.cpp

    Invalid character escape '\w'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
```

**Comment by dcangulo** [comment]
@abervoet Just to confirm, https://github.com/Kudo/react-native-v8/commit/5a2107fc986cc963470e4fb14ae85c58d41c3520 works?

**Comment by abervoet** [comment]
> @abervoet Just to confirm, [Kudo/react-native-v8@5a2107f](https://github.com/Kudo/react-native-v8/commit/5a2107fc986cc963470e4fb14ae85c58d41c3520) works? Because, I don't have a windows machine to test on.

Their exact code (diff) from the link, copied to your `android/build.gradle` file, works yes.
```
import org.apache.tools.ant.taskdefs.condition.Os
...
String toPlatformFileString(File path) {
  def result = path.toString()
  if (Os.isFamily(Os.FAMILY_WINDOWS)) {
    result = result.replace(File.separatorChar, '/' as char)
  }
  return result
}

externalNativeBuild {
      cmake {
        cppFlags "-O2 -frtti -fexceptions -Wall -fstack-protector-all"
        arguments "-DNODE_MODULES_DIR=${toPlatformFileString(rootDir)}/../node_modules"
      }
    }
```


Without :
![image](https://github.com/dcangulo/react-native-pkce-challenge/assets/22788933/7f581898-e586-4e01-8a3f-eb711afabdee)


With :
![image](https://github.com/dcangulo/react-native-pkce-challenge/assets/22788933/4c5bab86-6ccf-4a43-992e-8c503e2c077f)

**Comment by abervoet** [comment]
I also encountered the C++ issue from previous ticket here https://github.com/dcangulo/react-native-pkce-challenge/issues/391 , solved by pulling the library directly from git instead of npm, as the fix has not been released yet.

**Comment by dcangulo** [comment]
[v5.3.1](https://github.com/dcangulo/react-native-pkce-challenge/releases/tag/v5.3.1) release should include the fix for this issue.

**Comment by abervoet** [comment]
I was able to build and run the app directly with v5.3.1
Thanks
