### ISSUE TITLE
ETA to release patch for nodejs resolution to find node_modules dir for android build

### ISSUE THREAD

**Issue by alanblins** [dcangulo/react-native-pkce-challenge#506]
Any plan to release the patch 5.3.2 for [fix: use nodejs resolution to find node_modules dir for android build](https://github.com/dcangulo/react-native-pkce-challenge/commit/14e834fb04298b2e2d8323c9b782e3f6051c62be) ?

**Comment by dcangulo** [comment]
[v5.3.2](https://github.com/dcangulo/react-native-pkce-challenge/releases/tag/v5.3.2) released with that fix.
