### ISSUE TITLE
With our App's target SDK as 34 Google is asking to update this dependency to target 34

### ISSUE THREAD

**Issue by jrahil** [dcangulo/react-native-pkce-challenge#507]
We have updated App's target SDK as 34 but now Google is asking to update this NPM dependency to target 34 which is not in our control and without this change they are not ready to approve the application for release. Please suggest about issue's solution.

**Comment by dcangulo** [comment]
@jrahil This project uses YOUR target SDK version, I didn't set any target project SDK in this project.

See:
- https://github.com/dcangulo/react-native-pkce-challenge/blob/main/android/build.gradle#L79
- https://github.com/dcangulo/react-native-pkce-challenge/blob/main/android/build.gradle#L51

Relevant Code:
- `targetSdkVersion getExtOrIntegerDefault("targetSdkVersion")`
- `return rootProject.ext.has(name) ? rootProject.ext.get(name) : (project.properties["PkceChallenge_" + name]).toInteger()`

Make sure that you have `targetSdkVersion` in your `android/build.gradle`.

I'm also using this package in production and recently released an update that Google approved.
