### ISSUE TITLE
Issues with latest react native build.

### ISSUE THREAD

**Issue by devon2018** [dcangulo/react-native-pkce-challenge#508]
Recently upgraded my react native version to  0.76.1 and getting an error when trying to run the app on ios `RNPkceChallengeSpec.h file was not found`

**Comment by devon2018** [comment]
Any chance of getting a fix in for this, its quite easy to reproduce by creating a fresh react native project with the latest version and importing the package.
<img width="827" alt="Screenshot 2024-11-04 at 11 44 05" src="https://github.com/user-attachments/assets/f9774d1c-c8bc-4d51-8d27-e2355ef0f204">

**Comment by MarlonAEC** [comment]
+1 on this one

**Comment by dcangulo** [comment]
Can you check if #509 works on iOS, it works on Android but I can't test on iOS yet as I'm on the old Xcode version.

You can use the following in `package.json`:
```json
"react-native-pkce-challenge": "git+ssh://git@github.com:dcangulo/react-native-pkce-challenge.git#076"
```

or 
```json
"react-native-pkce-challenge": "git+https://github.com/dcangulo/react-native-pkce-challenge.git#076"
```

**Comment by MarlonAEC** [comment]
I will try it right now I spent the whole morning trying to solve this. Keep you posted

**Comment by MarlonAEC** [comment]
I'm still getting this error:
```
In file included from /Users/maespinosa/Documents/mobile-app/client/node_modules/react-native-pkce-challenge/ios/PkceChallenge.mm:1:
/Users/maespinosa/Documents/mobile-app/client/node_modules/react-native-pkce-challenge/ios/PkceChallenge.h:6:9: fatal error: 'RNPkceChallengeSpec.h' file not found
#import "RNPkceChallengeSpec.h"
```

**Comment by devon2018** [comment]
I ended up building out some native functionality in Kotlin and Swift, i put my code up here https://gist.github.com/devon2018/a8f3b2fb11d262bb7f052bc3b2326c90

**Comment by MarlonAEC** [comment]
That's not going to work for me because a third party did the implementation that is using this package in my source code and it's hard to tell how this will affect other modules and integrations, so I would prefer to get the update right. But I do appreciate sharing your code! That will be my last resource if I cannot get this updated. @dcangulo Looking at your PR I noticed this https://github.com/dcangulo/react-native-pkce-challenge/actions/runs/11814980358/job/32915173906?pr=509#step:6:21 your pipeline is failing to generate some code, maybe that's why there is a header missing?

**Comment by MarlonAEC** [comment]
Hey @dcangulo not to rush you but would you happen to have any updates on this? So far this is the only thing on my code blocking my upgrade. I'm more than happy to help you debug or test IOS if you need it. Pin me if you want to connect on the matter. Regards!

**Comment by dcangulo** [comment]
[v6.0.1](https://github.com/dcangulo/react-native-pkce-challenge/releases/tag/v6.0.1) works for me on Vanilla React Native v0.76.2 - iOS and Android - New Architecture

**Comment by MarlonAEC** [comment]
Indeed it worked thanks!
